Arcu detection
UBC-Snowbots/Snowflake pull request #419
Opened 2022-08-02 21:34 UTC by Roozki

## Please fill out the following before requesting review on this PR

### Description
Added package to scan and relay arcu codes for CIRC tasks

### Testing Done
quickly tested with the CIRC 2022 arcu dictionary on an ipad. Worked very accurately

### Resolved Issues
partially resolves arcu detection issue

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [ ] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in `src/sample_package` for examples.
- [ ] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `src/sample_package`
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
***Feel free to make additions of things that we should be checking to this file if you think there's something missing!!!!***

2022-08-09 20:35 UTC, ihsan314 requested changes
Make this branch up to date by fetching and rebasing, and then run the formatting script like so: `./clang-format/fix_formatting.sh master`. Commit the resulting changes, push and then request my review when you're done.

Also do we need `data.cpp` in the cameras package?

2022-08-09 20:35 UTC, ihsan314 commented on src/cameras/src/ImageSaver.cpp
> +    shutter2                  = nh.subscribe(shutter2_topic, queue_size2, &ImageSaver::subscriberCallBackShutter2, this);
Not urgent given competition is around but it may be helpful to use a more descriptive name for the callbacks

2022-08-09 20:35 UTC, ihsan314 commented on src/cameras/src/ImageSaver.cpp
> +      PicsToTake1 -= 1;void subscriberCallBack(const sensor_msgs::Image::ConstPtr& image);
```suggestion
      PicsToTake1 -= 1;
```

2022-08-09 20:35 UTC, ihsan314 commented on src/cameras/src/ImageSaver.cpp
> +      picCounter2 ++;
```suggestion
      picCounter2++;
```

2022-08-09 20:37 UTC, Roozki commented
nope, ill remove data.cpp

2022-08-14 04:26 UTC, ihsan314 approved these changes
Let's squash and merge this.

2022-08-14 04:26 UTC, merged